apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pg-k8s-backup.shortname" . }}-postgres-secret
  labels:
    {{- include "pg-k8s-backup.labels" . | nindent 4 }}
type: Opaque
data:
  PGUSER:  {{ .Values.postgres.creds.username | b64enc | quote }}
  PGPASSWORD: {{ .Values.postgres.creds.password | b64enc | quote }}